# Generated by Django 4.0.6 on 2022-07-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=100)),
                ('Salary', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
                ('Status', models.BooleanField()),
            ],
        ),
    ]
