# Generated by Django 4.0.6 on 2022-07-09 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emp_info',
            options={'verbose_name': 'Banglore'},
        ),
    ]
