# Generated by Django 4.0.6 on 2022-07-10 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_alter_emp_info_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emp_info',
            options={},
        ),
    ]
